export enum Genre {
  COMICSERIES_ACTION = "COMICSERIES_ACTION",
  COMICSERIES_COMEDY = "COMICSERIES_COMEDY",
  COMICSERIES_CRIME = "COMICSERIES_CRIME",
  COMICSERIES_DRAMA = "COMICSERIES_DRAMA",
  COMICSERIES_DYSTOPIA = "COMICSERIES_DYSTOPIA",
  COMICSERIES_EDUCATIONAL = "COMICSERIES_EDUCATIONAL",
  COMICSERIES_FANTASY = "COMICSERIES_FANTASY",
  COMICSERIES_HIGH_SCHOOL = "COMICSERIES_HIGH_SCHOOL",
  COMICSERIES_HISTORICAL = "COMICSERIES_HISTORICAL",
  COMICSERIES_HORROR = "COMICSERIES_HORROR",
  COMICSERIES_HAREM = "COMICSERIES_HAREM",
  COMICSERIES_ISEKAI = "COMICSERIES_ISEKAI",
  COMICSERIES_MYSTERY = "COMICSERIES_MYSTERY",
  COMICSERIES_ROMANCE = "COMICSERIES_ROMANCE",
  COMICSERIES_SCI_FI = "COMICSERIES_SCI_FI",
  COMICSERIES_SLICE_OF_LIFE = "COMICSERIES_SLICE_OF_LIFE",
  COMICSERIES_SUPERHERO = "COMICSERIES_SUPERHERO",
  COMICSERIES_SUPERNATURAL = "COMICSERIES_SUPERNATURAL",
  COMICSERIES_BL = "COMICSERIES_BL",
  COMICSERIES_GL = "COMICSERIES_GL",
  COMICSERIES_LGBTQ = "COMICSERIES_LGBTQ",
  COMICSERIES_THRILLER = "COMICSERIES_THRILLER",
  COMICSERIES_ZOMBIES = "COMICSERIES_ZOMBIES",
  COMICSERIES_POST_APOCALYPTIC = "COMICSERIES_POST_APOCALYPTIC",
  COMICSERIES_SPORTS = "COMICSERIES_SPORTS",
  COMICSERIES_ANIMALS = "COMICSERIES_ANIMALS",
  COMICSERIES_GAMING = "COMICSERIES_GAMING",
}

export function getPrettyGenre(genre: Genre): string {
  switch(genre){
    case Genre.COMICSERIES_LGBTQ:
      return "LGBTQ+"
    case Genre.COMICSERIES_BL:
      return "BL"
    case Genre.COMICSERIES_GL:
      return "GL"
    case Genre.COMICSERIES_SCI_FI:
      return "Sci-Fi"
    default:
      return genre.split("_").map(word => { return word[0].toUpperCase() + word.slice(1).toLowerCase()} ).slice(1).join(" ")
  }
}