const rawAllLanguages = [
  "ENGLISH",
  "SPANISH",
  "FRENCH",
  "KOREAN",
  "JAPANESE",
  "CHINESE",
  "AFAR",
  "ABKHAZIAN",
  "AVESTAN",
  "AFRIKAANS",
  "AKAN",
  "AMHARIC",
  "ARAGONESE",
  "ARABIC",
  "ASSAMESE",
  "AVARIC",
  "AYMARA",
  "AZERBAIJANI",
  "BASHKIR",
  "BELARUSIAN",
  "BULGARIAN",
  "BIHARI_LANGUAGES",
  "BISLAMA",
  "BAMBARA",
  "BENGALI",
  "TIBETAN",
  "BRETON",
  "BOSNIAN",
  "VALENCIAN_CATALAN",
  "CHAMORRO",
  "CHECHEN",
  "CORSICAN",
  "CREE",
  "CZECH",
  "CHURCH_SLAVONIC",
  "CHUVASH",
  "WELSH",
  "DANISH",
  "GERMAN",
  "DHIVEHI_MALDIVIAN",
  "DZONGKHA",
  "EWE",
  "GREEK",
  "ESPERANTO",
  "ESTONIAN",
  "BASQUE",
  "FARSI",
  "FULAH",
  "FINNISH",
  "FIJIAN",
  "FAROESE",
  "WESTERN_FRISIAN",
  "IRISH",
  "GAELIC",
  "GALICIAN",
  "GUARANI",
  "GUJARATI",
  "MANX",
  "HAUSA",
  "HEBREW",
  "HINDI",
  "HIRI_MOTU",
  "CROATIAN",
  "HAITIAN_CREOLE",
  "HUNGARIAN",
  "ARMENIAN",
  "HERERO",
  "INTERLINGUA",
  "INDONESIAN",
  "INTERLINGUE_OCCIDENTAL",
  "IGBO",
  "NUOSU_SICHUAN_YI",
  "INUPIAQ",
  "IDO",
  "ICELANDIC",
  "ITALIAN",
  "INUKTITUT",
  "JAVANESE",
  "GEORGIAN",
  "KONGO",
  "GIKUYU",
  "KWANYAMA",
  "KAZAKH",
  "KALAALLISUT_GREENLANDIC",
  "CENTRAL_KHMER",
  "KANNADA",
  "KANURI",
  "KASHMIRI",
  "KURDISH",
  "KOMI",
  "CORNISH",
  "KYRGYZ",
  "LATIN",
  "LETZEBURGESCH",
  "GANDA",
  "LIMBURGISH",
  "LINGALA",
  "LAO",
  "LITHUANIAN",
  "LUBA_KATANGA",
  "LATVIAN",
  "MALAGASY",
  "MARSHALLESE",
  "MAORI",
  "MACEDONIAN",
  "MALAYALAM",
  "MONGOLIAN",
  "MARATHI",
  "MALAY",
  "MALTESE",
  "BURMESE",
  "NAURU",
  "NORWEGIAN_BOKMAL",
  "NORTH_NDEBELE",
  "NEPALI",
  "NDONGA",
  "DUTCH_FLEMISH",
  "NORWEGIAN_NYNORSK",
  "NORWEGIAN",
  "SOUTH_NDEBELE",
  "NAVAJO",
  "CHICHEWA_CHEWA_NYANJA",
  "OCCITAN",
  "OJIBWA",
  "OROMO",
  "ORIYA",
  "OSSETIAN",
  "PUNJABI",
  "PALI",
  "POLISH",
  "PASHTO",
  "PORTUGUESE",
  "QUECHUA",
  "ROMANSH",
  "RUNDI",
  "ROMANIAN_MOLDOVAN",
  "RUSSIAN",
  "KINYARWANDA",
  "SANSKRIT",
  "SARDINIAN",
  "SINDHI",
  "NORTHERN_SAMI",
  "SANGO",
  "SINHALA",
  "SLOVAK",
  "SLOVENIAN",
  "SAMOAN",
  "SHONA",
  "SOMALI",
  "ALBANIAN",
  "SERBIAN",
  "SWATI",
  "SOTHO",
  "SUNDANESE",
  "SWEDISH",
  "SWAHILI",
  "TAMIL",
  "TELUGU",
  "TAJIK",
  "THAI",
  "TIGRINYA",
  "TURKMEN",
  "TAGALOG",
  "TSWANA",
  "TONGA",
  "TURKISH",
  "TSONGA",
  "TATAR",
  "TWI",
  "TAHITIAN",
  "UYGHUR",
  "UKRAINIAN",
  "URDU",
  "UZBEK",
  "VENDA",
  "VIETNAMESE",
  "VOLAPUK",
  "WALLOON",
  "WOLOF",
  "XHOSA",
  "YIDDISH",
  "YORUBA",
  "ZHUANG",
  "ZULU",
]

const allLanguagesSorted = rawAllLanguages.sort()

const primaryLanguages = [
  "ENGLISH",
  "SPANISH",
  "FRENCH",
  "KOREAN",
  "JAPANESE",
  "CHINESE",
]

const primaryLanguagesSet = new Set(primaryLanguages)

const allLanguages = [...primaryLanguages, ...allLanguagesSorted.filter(lang => !primaryLanguagesSet.has(lang))]

const allLanguagesSet = new Set(allLanguages);

function getPrettyLanguage(language){
  if (!language) return
  return language.split("_").map(word => { return word[0].toUpperCase() + word.slice(1).toLowerCase()} ).join(" ")
}

function safeLanguage(language){
  if (!language) return
  const item = language.toUpperCase().trim()
  if (!allLanguagesSet.has(item)){ throw new Error("Invalid Language") }
  return item
}

module.exports = {
  allLanguages,
  allLanguagesSet,
  getPrettyLanguage,
  safeLanguage,
}