const bamTags = [
  "ART_ADORABLE",
  "ART_IMAGINATIVE",
  "ART_PLAYFUL",
  "ART_CUTE",
  "CHARACTER_CHARMING",
  "CHARACTER_WITTY",
  "ART_FANTASTICAL",
  "PLOT_MAGICAL",
  "ART_FABULOUS",
  "ART_BEAUTIFUL",
  "ART_ICONIC",
  "PLOT_CLEVER",
  "PLOT_HEARTWARMING",
  "PLOT_MOVING",
  "PLOT_ROMANTIC",
  "PLOT_HOT",
  "PLOT_ATEARJERKER",
  "PLOT_CHILLING",
  "PLOT_FUNNY", 
  "PLOT_ACTIONPACKED",
  "PLOT_AHIDDENGEM",
  "PLOT_AMUSTREAD",
  "PLOT_GRIPPING",
  "PLOT_UNFORGETTABLE",
  "PLOT_WELLPACED",
  "PLOT_WELLWRITTEN",
];

const readableBamTag = {
  'ART_ADORABLE': '🥰 Adorable',
  'ART_IMAGINATIVE': '🧠 Imaginative',
  'ART_FANTASTICAL': '🦄 Fantastical',
  'ART_FABULOUS': '💅 Fabulous',
  'ART_ICONIC': '🌟 Iconic',
  'ART_PLAYFUL': '🤪 Playful',
  'ART_CUTE': '🐣 Cute',
  'ART_PUNK': '🤘 Punk',
  'PLOT_CLEVER': '🤓 Clever',
  'PLOT_MOVING': '🥺 Moving',
  'PLOT_ATEARJERKER': '😭 A tear-jerker',
  'PLOT_HEARTBREAKING': '💔 Heart-breaking',
  'PLOT_CHILLING': '🔪 Chilling',
  'PLOT_HORRIFYING': '😱 Horrifying',
  'PLOT_FUNNY': '😂 Funny',
  'PLOT_ABSOLUTELYHILARIOUS': '🤣 Absolutely hilarious',
  'PLOT_AHIDDENGEM': '💎 A Hidden Gem',
  'PLOT_UNFORGETTABLE': '👌 Unforgettable',
  'PLOT_WELLPACED': '🏃‍♂️ Well-paced',
  'PLOT_WELLWRITTEN': '📝 Well-written',
  'ART_BEAUTIFUL': '🌺 Beautiful Art',
  'CHARACTER_CHARMING': '😊 Charming',
  'CHARACTER_QUIRKY': '🤪 Quirky',
  'CHARACTER_WITTY': '🤓 Witty',
  'PLOT_GRIPPING': '🧗‍♂️ Gripping',
  'PLOT_HEARTWARMING': '🤗 Heartwarming',
  'PLOT_ROMANTIC': '🌹 Romantic',
  'PLOT_ACTIONPACKED': '💥 Action packed',
  'PLOT_AMUSTREAD': '💯 A must read',
  'PLOT_MAGICAL': '🧙‍ Magical',
  'CHARACTER_CHARACTERDRIVEN': '🎭 Character driven',
  'PLOT_HOT': '🌶️ Hot',
}

const bamTagsSet = new Set(bamTags);

module.exports = {
  bamTags,
  readableBamTag,
  bamTagsSet
};