export enum RecommendationTag {
  ART_ADORABLE = "ART_ADORABLE",
  ART_IMAGINATIVE = "ART_IMAGINATIVE",
  ART_PLAYFUL = "ART_PLAYFUL",
  ART_CUTE = "ART_CUTE",
  CHARACTER_CHARMING = "CHARACTER_CHARMING",
  CHARACTER_WITTY = "CHARACTER_WITTY",
  ART_FANTASTICAL = "ART_FANTASTICAL",
  PLOT_MAGICAL = "PLOT_MAGICAL",
  ART_FABULOUS = "ART_FABULOUS",
  ART_BEAUTIFUL = "ART_BEAUTIFUL",
  ART_ICONIC = "ART_ICONIC",
  PLOT_CLEVER = "PLOT_CLEVER",
  PLOT_HEARTWARMING = "PLOT_HEARTWARMING",
  PLOT_MOVING = "PLOT_MOVING",
  PLOT_ROMANTIC = "PLOT_ROMANTIC",
  PLOT_HOT = "PLOT_HOT",
  PLOT_ATEARJERKER = "PLOT_ATEARJERKER",
  PLOT_CHILLING = "PLOT_CHILLING",
  PLOT_FUNNY = "PLOT_FUNNY", 
  PLOT_ACTIONPACKED = "PLOT_ACTIONPACKED",
  PLOT_AHIDDENGEM = "PLOT_AHIDDENGEM",
  PLOT_AMUSTREAD = "PLOT_AMUSTREAD",
  PLOT_GRIPPING = "PLOT_GRIPPING",
  PLOT_UNFORGETTABLE = "PLOT_UNFORGETTABLE",
  PLOT_WELLPACED = "PLOT_WELLPACED",
  PLOT_WELLWRITTEN = "PLOT_WELLWRITTEN",
}

enum DeprecatedRecommendationTag {
  ART_PUNK = "ART_PUNK",
  PLOT_HORRIFYING = "PLOT_HORRIFYING",
  PLOT_ABSOLUTELYHILARIOUS = "PLOT_ABSOLUTELYHILARIOUS",
  CHARACTER_QUIRKY = "CHARACTER_QUIRKY",
  CHARACTER_CHARACTERDRIVEN = "CHARACTER_CHARACTERDRIVEN",
}

export const allRecommendations: RecommendationTag[] = Object.values(RecommendationTag)

export const prettyRecommendationTag: { [key in RecommendationTag | DeprecatedRecommendationTag]: string } = {
  [RecommendationTag.ART_ADORABLE]: '🥰 Adorable',
  [RecommendationTag.ART_IMAGINATIVE]: '🧠 Imaginative',
  [RecommendationTag.ART_FANTASTICAL]: '🦄 Fantastical',
  [RecommendationTag.ART_FABULOUS]: '💅 Fabulous',
  [RecommendationTag.ART_ICONIC]: '🌟 Iconic',
  [RecommendationTag.ART_PLAYFUL]: '🤪 Playful',
  [RecommendationTag.ART_CUTE]: '🐣 Cute',
  [RecommendationTag.PLOT_CLEVER]: '🤓 Clever',
  [RecommendationTag.PLOT_MOVING]: '🥺 Moving',
  [RecommendationTag.PLOT_ATEARJERKER]: '😭 A tear-jerker',
  [RecommendationTag.PLOT_HEARTWARMING]: '🤗 Heartwarming',
  [RecommendationTag.PLOT_FUNNY]: '😂 Funny',
  [RecommendationTag.PLOT_AHIDDENGEM]: '💎 A Hidden Gem',
  [RecommendationTag.PLOT_UNFORGETTABLE]: '👌 Unforgettable',
  [RecommendationTag.PLOT_WELLPACED]: '🏃‍♂️ Well-paced',
  [RecommendationTag.PLOT_WELLWRITTEN]: '📝 Well-written',
  [RecommendationTag.PLOT_CHILLING]: '🧊 Chilling',
  [RecommendationTag.ART_BEAUTIFUL]: '🌺 Beautiful Art',
  [RecommendationTag.CHARACTER_CHARMING]: '😊 Charming',
  [RecommendationTag.CHARACTER_WITTY]: '🤓 Witty',
  [RecommendationTag.PLOT_GRIPPING]: '🧗‍♂️ Gripping',
  [RecommendationTag.PLOT_ROMANTIC]: '🌹 Romantic',
  [RecommendationTag.PLOT_ACTIONPACKED]: '💥 Action packed',
  [RecommendationTag.PLOT_AMUSTREAD]: '💯 A must read',
  [RecommendationTag.PLOT_MAGICAL]: '🧙‍ Magical',
  [RecommendationTag.PLOT_HOT]: '🌶️ Hot',
  [DeprecatedRecommendationTag.ART_PUNK]: '🤘 Punk',
  [DeprecatedRecommendationTag.PLOT_HORRIFYING]: '😱 Horrifying',
  [DeprecatedRecommendationTag.PLOT_ABSOLUTELYHILARIOUS]: '🤣 Absolutely hilarious',
  [DeprecatedRecommendationTag.CHARACTER_QUIRKY]: '🤪 Quirky',
  [DeprecatedRecommendationTag.CHARACTER_CHARACTERDRIVEN]: '🎭 Character driven',
}