export const reportTypes = {
  INTELLECTUAL_PROPERTY_VIOLATION: 'INTELLECTUAL_PROPERTY_VIOLATION',
  GENERATIVE_AI_CONTENT: 'GENERATIVE_AI_CONTENT',
  CONTAINS_SEXUALLY_EXPLICIT_CONTENT: 'CONTAINS_SEXUALLY_EXPLICIT_CONTENT',
  DECEPTIVE_OR_FRAUDULENT_CONTENT: 'DECEPTIVE_OR_FRAUDULENT_CONTENT',
  CONTAINS_HATE_SPEECH: 'CONTAINS_HATE_SPEECH',
  IS_SPAM: 'IS_SPAM',
  CONTAINS_UNLAWFUL_CONTENT: 'CONTAINS_UNLAWFUL_CONTENT',
}

export const reportConstants = {
  'INTELLECTUAL_PROPERTY_VIOLATION': `Violation of intellectual property rights`,
  'GENERATIVE_AI_CONTENT': `Contains generative AI content`,
  'CONTAINS_SEXUALLY_EXPLICIT_CONTENT': `Contains genitalia, breasts or depicts a sex act`,
  'DECEPTIVE_OR_FRAUDULENT_CONTENT': `Deceptive or Fraudulent Content`,
  'CONTAINS_HATE_SPEECH': `Contains hate speech`,
  'IS_SPAM': `Is Spam`,
  'CONTAINS_UNLAWFUL_CONTENT': `Contains unlawful content`,
};
